controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

fetch_all:
    path: /articulos
    controller: App\Controller\ArticuloController::fetch_all